language: cpp
dist: bionic
sudo: required

env:
  # Turn off all RPC layers by default. They will be enabled one-by-one in the
  # build matrix
  global:
    - HCL_COMMUNICATION=THALLIUM
# Install APT dependencies
addons:
  apt:
    packages:
      - libboost-dev
      - mpich
      - libmpich-dev

thallium_deps: &thallium_deps
  - ./ci/install_libfabric.sh
  - ./ci/install_mercury.sh
  - ./ci/install_argobots.sh
  - ./ci/install_margo.sh
  - ./ci/install_thallium.sh

matrix:
  include:
    - env: HCL_COMMUNICATION=THALLIUM
      before_install: *thallium_deps

script: ./ci/install_hcl.sh
