#ifndef HCL_COMMON_HCL_PROFILER_H
#define HCL_COMMON_HCL_PROFILER_H
#if defined(HCL_HAS_CONFIG)
#include <hcl/hcl_config.hpp>
#else
#error "no config"
#endif

#ifdef HCL_PROFILER_DLIO_PROFILER  // DLIO_PROFILER
#include <dlio_profiler/dlio_profiler.h>
#endif

#ifdef __cplusplus
#ifdef HCL_PROFILER_NONE
#define HCL_CPP_FUNCTION() HCL_NOOP_MACRO
#define HCL_CPP_FUNCTION_UPDATE(key, value) HCL_NOOP_MACRO
#define HCL_CPP_REGION(name) HCL_NOOP_MACRO
#define HCL_CPP_REGION_UPDATE(name) HCL_NOOP_MACRO
#define HCL_CPP_BLOCK_START(name) HCL_NOOP_MACRO
#define HCL_CPP_BLOCK_END(name) HCL_NOOP_MACRO
#define HCL_CPP_BLOCK_UPDATE(name) HCL_NOOP_MACRO
#define HCL_PROFILER_CPP_INIT() HCL_NOOP_MACRO
#define HCL_PROFILER_CPP_FINI() HCL_NOOP_MACRO
#elif defined(HCL_PROFILER_DLIO_PROFILER)  // DLIO_PROFILER
#define HCL_CPP_FUNCTION() DLIO_PROFILER_CPP_FUNCTION()
#define HCL_CPP_FUNCTION_UPDATE(key, value) \
  DLIO_PROFILER_CPP_FUNCTION_UPDATE(key, value)
#define HCL_CPP_REGION(name) DLIO_PROFILER_CPP_REGION(name)

#define HCL_CPP_BLOCK_START(name) DLIO_PROFILER_CPP_REGION_START((name))
#define HCL_CPP_BLOCK_END(name) DLIO_PROFILER_CPP_REGION_END((name))
#define HCL_CPP_BLOCK_UPDATE(name) \
  DLIO_PROFILER_CPP_REGION_DYN_UPDATE(name, key, value)
#define HCL_CPP_REGION_UPDATE(name, key, value) \
  DLIO_PROFILER_CPP_REGION_UPDATE(name, key, value)
#define HCL_PROFILER_CPP_INIT(logfile) \
  DLIO_PROFILER_CPP_INIT_NO_BIND(logfile, NULL, NULL)
#define HCL_PROFILER_CPP_FINI() DLIO_PROFILER_CPP_FINI()
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef HCL_PROFILER_NONE
#define HCL_C_FUNCTION_START() HCL_NOOP_MACRO
#define HCL_C_FUNCTION_END() HCL_NOOP_MACRO
#define HCL_C_FUNCTION_UPDATE_INT(key, value) HCL_NOOP_MACRO
#define HCL_C_FUNCTION_UPDATE_STR(key, value) HCL_NOOP_MACRO
#define HCL_C_REGION_START(name) HCL_NOOP_MACRO
#define HCL_C_REGION_END(name) HCL_NOOP_MACRO
#define HCL_C_REGION_UPDATE_INT(name) HCL_NOOP_MACRO
#define HCL_C_REGION_UPDATE_STR(name) HCL_NOOP_MACRO
#define HCL_PROFILER_C_INIT() HCL_NOOP_MACRO
#define HCL_PROFILER_C_FINI() HCL_NOOP_MACRO
#elif defined(HCL_PROFILER_DLIO_PROFILER)  // DLIO_PROFILER
#define HCL_C_FUNCTION_START() DLIO_PROFILER_C_FUNCTION_START()
#define HCL_C_FUNCTION_END() DLIO_PROFILER_C_FUNCTION_END()
#define HCL_C_FUNCTION_UPDATE_INT(key, value) \
  DLIO_PROFILER_C_FUNCTION_UPDATE_INT((key), (value))
#define HCL_C_FUNCTION_UPDATE_STR(key, value) \
  DLIO_PROFILER_C_FUNCTION_UPDATE_STR((key), (value))
#define HCL_C_REGION_START(name) DLIO_PROFILER_C_REGION_START((name))
#define HCL_C_REGION_END(name) DLIO_PROFILER_C_REGION_END((name))
#define HCL_C_REGION_UPDATE_INT(name) \
  DLIO_PROFILER_C_REGION_UPDATE_INT((name), (key), (value))
#define HCL_C_REGION_UPDATE_STR(name) \
  DLIO_PROFILER_C_REGION_UPDATE_STR((name), (key), (value))
#define HCL_PROFILER_C_INIT(logfile) \
  DLIO_PROFILER_C_INIT_NO_BIND(logfile, NULL, NULL)
#define HCL_PROFILER_C_FINI() DLIO_PROFILER_C_FINI()
#endif

#ifdef __cplusplus
}
#endif

#endif  // HCL_COMMON_HCL_PROFILER_H