#!/bin/bash
eval $SPACK_SOURCE 
spack env activate -p ${INSTALL_DIR}
export INSTALL_DIR=/root/install
export VIEW_DIR=/root/install/.spack-env/view
export SPACK_DIR=/root/spack

ls ${VIEW_DIR}/lib/cmake ${VIEW_DIR}/lib64/cmake

mkdir build
pushd build

CXXFLAGS="-I${VIEW_DIR}/include"
LDFLAGS="-L${VIEW_DIR}/lib"
CMAKE_C_COMPILER=`which gcc`
CMAKE_CXX_COMPILER=`which g++`

echo ${VIEW_DIR}

echo cmake \
    -DCMAKE_INSTALL_PREFIX=${VIEW_DIR} \
    -DCMAKE_PREFIX_PATH=${VIEW_DIR} \
    -DCMAKE_BUILD_RPATH="${VIEW_DIR}/lib" \
    -DCMAKE_INSTALL_RPATH="${VIEW_DIR}/lib" \
    -DCMAKE_CXX_FLAGS="-I${VIEW_DIR}/include -L${VIEW_DIR}/lib" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} \
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} \
    -DHCL_COMMUNICATION=${HCL_COMMUNICATION} \
    -DHCL_COMMUNICATION_PROTOCOL=${HCL_COMMUNICATION_PROTOCOL} \
    -DHCL_ENABLE_TESTING=ON \
    ../

cmake \
    -DCMAKE_INSTALL_PREFIX=${VIEW_DIR} \
    -DCMAKE_PREFIX_PATH=${VIEW_DIR} \
    -DCMAKE_BUILD_RPATH="${VIEW_DIR}/lib" \
    -DCMAKE_INSTALL_RPATH="${VIEW_DIR}/lib" \
    -DCMAKE_CXX_FLAGS="-I${VIEW_DIR}/include -L${VIEW_DIR}/lib" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} \
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} \
    -DHCL_COMMUNICATION=${HCL_COMMUNICATION} \
    -DHCL_COMMUNICATION_PROTOCOL=${HCL_COMMUNICATION_PROTOCOL} \
    -DHCL_ENABLE_TESTING=ON \
    ../

cmake --build . -- -j 2 VERBOSE=1 || exit 1

popd
