# This is a basic workflow to help you get started with Actions

name: cmake

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push,pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  LOCAL: local

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: hdevarajan92/hcl-deps:0.0.2
    strategy:
      fail-fast: false
      matrix:
        THALLIUM_TCP: ["ON"]
        THALLIUM_ROCE: ["OFF"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Build
        env:
          HCL_ENABLE_THALLIUM_TCP: ${{ matrix.THALLIUM_TCP }}
          HCL_ENABLE_THALLIUM_ROCE: ${{ matrix.THALLIUM_ROCE }}
        run: ci/install_hcl.sh
      - name: Test
        env:
          HCL_ENABLE_THALLIUM_TCP: ${{ matrix.THALLIUM_TCP }}
          HCL_ENABLE_THALLIUM_ROCE: ${{ matrix.THALLIUM_ROCE }}
        run: ci/run_hcl.sh
